
project_id = "acsqneuzkukmvtfmbphb"

[functions.analyze-food]
verify_jwt = true

[functions.analyze-food-by-name]
verify_jwt = true

[functions.meal-suggestions]
verify_jwt = true

[functions.rtdn-webhook]
verify_jwt = false

[functions.subscription-manager]
verify_jwt = true
