
project_id = "acsqneuzkukmvtfmbphb"

[functions.analyze-food]
verify_jwt = true

[functions.analyze-food-by-name]
verify_jwt = true

[functions.diet-assistant]
verify_jwt = true

[functions.meal-suggestions]
verify_jwt = true
