// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://acsqneuzkukmvtfmbphb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjc3FuZXV6a3VrbXZ0Zm1icGhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NTc3MzQsImV4cCI6MjA2ODIzMzczNH0.YPi7bwjLsvEzqa8tBH05DU3yN0yPSH-qHNnEqKI2BR8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});