require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '15.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorLocalNotifications', :path => '../../node_modules/@capacitor/local-notifications'
  pod 'CodetrixStudioCapacitorGoogleAuth', :path => '../../node_modules/@codetrix-studio/capacitor-google-auth'
  pod 'RevenuecatPurchasesCapacitor', :path => '../../node_modules/@revenuecat/purchases-capacitor'
  pod 'RevenuecatPurchasesCapacitorUi', :path => '../../node_modules/@revenuecat/purchases-capacitor-ui'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)

  # Add privacy manifests to Google Sign-In frameworks
  privacy_manifest_content = <<-XML
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>NSPrivacyTracking</key>
    <false/>
    <key>NSPrivacyTrackingDomains</key>
    <array/>
    <key>NSPrivacyCollectedDataTypes</key>
    <array/>
    <key>NSPrivacyAccessedAPITypes</key>
    <array>
        <dict>
            <key>NSPrivacyAccessedAPIType</key>
            <string>NSPrivacyAccessedAPICategoryUserDefaults</string>
            <key>NSPrivacyAccessedAPITypeReasons</key>
            <array>
                <string>CA92.1</string>
            </array>
        </dict>
        <dict>
            <key>NSPrivacyAccessedAPIType</key>
            <string>NSPrivacyAccessedAPICategoryFileTimestamp</string>
            <key>NSPrivacyAccessedAPITypeReasons</key>
            <array>
                <string>C617.1</string>
            </array>
        </dict>
    </array>
</dict>
</plist>
  XML

  ['GoogleSignIn', 'GTMAppAuth', 'GTMSessionFetcher'].each do |framework_name|
    installer.pods_project.targets.each do |target|
      if target.name == framework_name
        puts "Adding PrivacyInfo.xcprivacy to #{framework_name}"

        # Find the framework's resource bundle path
        framework_path = "Pods/#{framework_name}"
        privacy_file_path = File.join(framework_path, "Resources/PrivacyInfo.xcprivacy")

        # Create Resources directory if it doesn't exist
        resources_dir = File.join(framework_path, "Resources")
        FileUtils.mkdir_p(resources_dir) unless File.directory?(resources_dir)

        # Write the privacy manifest
        File.write(privacy_file_path, privacy_manifest_content)

        # Add to target's resources
        privacy_file_ref = target.project.main_group.find_file_by_path(privacy_file_path)
        unless privacy_file_ref
          privacy_file_ref = target.project.main_group.new_reference(privacy_file_path)
        end

        target.resources_build_phase.add_file_reference(privacy_file_ref) unless target.resources_build_phase.files_references.include?(privacy_file_ref)
      end
    end
  end
end
